/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MessageViewerPanel.java
 *
 * Created on 23 avr. 2009, 10:25:01
 */

package rmiage.framework.client.gui;

/**
 *
 * @author gcarrier
 */
public class MessageViewerPanel extends javax.swing.JPanel {

    /** Creates new form MessageViewerPanel */
    public MessageViewerPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rmiage/framework/client/resources/empty_profile.png"))); // NOI18N
        add(jLabel1, java.awt.BorderLayout.WEST);

        jLabel2.setText("By an unknown author, at an unknown date");
        add(jLabel2, java.awt.BorderLayout.NORTH);

        jTextPane1.setEditable(false);
        jTextPane1.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis massa metus, tristique nec, cursus quis, tincidunt eget, felis.\n\nQuisque aliquam arcu imperdiet lectus. In facilisis dictum lectus. Sed lacinia posuere augue. Vestibulum eu nibh et diam bibendum feugiat.");
        jScrollPane1.setViewportView(jTextPane1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

}
